---
apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artificats:
    - image: rahulroot/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
